version: '3.8'
services:
  ap:
    restart: always
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: /start
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    tty: true
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: django-db
      MYSQL_USER: django
      MYSQL_PASSWORD: django
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "4307:3306"
    restart: always
    tty: true
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    tty: true
  celery:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    volumes:
      - .:/app
    image: celery:latest
    depends_on:
      - redis
      - db
    volumes_from:
      - ap
    working_dir: /app
    tty: true
    command: /start-celeryworker
  celery_monitor:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    volumes:
      - .:/app
    image: celery:latest
    depends_on:
      - redis
      - db
    volumes_from:
      - ap
    working_dir: /app
    tty: true
    command: /start-celerycamera
  celery_flower:
    restart: always
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    volumes:
      - .:/app
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db
    tty: true
    command: /start-celeryflower

